### PR TITLE
Add more JUnit or fix code

### PR DESCRIPTION
**Pull request by TongThanaphon**
Did we're need more JUnit?
Did anyone found bug?
Did anyone think my code should more improve?

### CODE REVIEW

**Comment by Vichacorn** [comment]
I think you should add testAverageException case, and some import didn't used.

**Comment by Driveiei** [comment]
Fix name attribute(n)

https://github.com/New-az/ExerciseUnitTest/blob/307f44184c7d236e317410fd7a2fae5c8e3d6eb8/src/Statistics.java#L35-L42

to be something like this :   
https://github.com/New-az/ExerciseUnitTest/blob/307f44184c7d236e317410fd7a2fae5c8e3d6eb8/src/Statistics.java#L64

Should be better. Others are ok now.

**Comment by TongThanaphon** [comment]
anything else?

**Comment by Vichacorn** [comment]
PASS!!

**Pull request merged**
