### PR TITLE
add more Junit

### PR DESCRIPTION
**Pull request by Vichacorn**
Did we're need more junit?
Did anyone found bugs more?

### CODE REVIEW

**Comment by Driveiei** [comment]
Can you add more test?
So less test case, I think.

**Comment by Vichacorn** [comment]
I think it should cover all case now.
@Driveiei @ThanaphonKeawjam

**Comment by TongThanaphon** [comment]
for(int k=0; k<array.length; k++) {
I think should create local variable for array.length.

**Comment by Vichacorn** [comment]
I'm fixed. anything else @Driveiei @ThanaphonKeawjam

**Comment by Driveiei** [comment]
It's OK now, I think.

**Comment by TongThanaphon** [comment]
It's Okay

**Pull request merged**
